#ifndef __XTRAINER_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __XTRAINER_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(XCB)

#endif // __XTRAINER_CONTROL_BOARD_LOG_COMPONENT_HPP__
