/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.2)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GENERATION is ON.

// Generated on: Sat Oct 10 17:26:00 2026


#include "XTrainerControlBoard_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(XTrainerControlBoardParamsCOMPONENT, "yarp.device.XTrainerControlBoard")
}


XTrainerControlBoard_ParamsParser::XTrainerControlBoard_ParamsParser()
{
}


std::vector<std::string> XTrainerControlBoard_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("axes");
    params.push_back("port");
    params.push_back("baudrate");
    params.push_back("ids");
    params.push_back("extra_id");
    return params;
}


bool XTrainerControlBoard_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="axes")
    {
        paramValue = std::to_string(m_axes);
        return true;
    }
    if (paramName =="port")
    {
        paramValue = m_port;
        return true;
    }
    if (paramName =="baudrate")
    {
        paramValue = std::to_string(m_baudrate);
        return true;
    }
    if (paramName =="ids")
    {
        std::ostringstream oss;
        oss << "( ";
        for (auto x : m_ids)
        {
            oss << x << " ";
        }
        oss << " )";
        paramValue = oss.str();
        return true;
    }
    if (paramName =="extra_id")
    {
        paramValue = std::to_string(m_extra_id);
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string XTrainerControlBoard_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      XTrainerControlBoard_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(XTrainerControlBoardParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter axes
    {
        if (config.check("axes"))
        {
            m_axes = config.find("axes").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'axes' using value:" << m_axes;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'axes' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Number of axes";
            return false;
        }
        prop_check.unput("axes");
    }

    //Parser of parameter port
    {
        if (config.check("port"))
        {
            m_port = config.find("port").asString();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'port' using value:" << m_port;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'port' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Name of the serial port";
            return false;
        }
        prop_check.unput("port");
    }

    //Parser of parameter baudrate
    {
        if (config.check("baudrate"))
        {
            m_baudrate = config.find("baudrate").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'baudrate' using value:" << m_baudrate;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'baudrate' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Baud rate of the serial port";
            return false;
        }
        prop_check.unput("baudrate");
    }

    //Parser of parameter ids
    {
        if (config.check("ids"))
        {
            {
                m_ids.clear();
                yarp::os::Bottle* tempBot = config.find("ids").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_ids.push_back(tempBot->get(i).asInt64());
                    }
                }
                else
                {
                     yCError(XTrainerControlBoardParamsCOMPONENT) <<"parameter 'ids' is not a properly formatted bottle";
                }
            }
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'ids' using value:" << m_ids;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'ids' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Motor IDs";
            return false;
        }
        prop_check.unput("ids");
    }

    //Parser of parameter extra_id
    {
        if (config.check("extra_id"))
        {
            m_extra_id = config.find("extra_id").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'extra_id' using value:" << m_extra_id;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'extra_id' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Extra motor ID";
            return false;
        }
        prop_check.unput("extra_id");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(XTrainerControlBoardParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(XTrainerControlBoardParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      XTrainerControlBoard_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: XTrainerControlBoard\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'axes': Number of axes\n");
    doc = doc + std::string("'port': Name of the serial port\n");
    doc = doc + std::string("'baudrate': Baud rate of the serial port\n");
    doc = doc + std::string("'ids': Motor IDs\n");
    doc = doc + std::string("'extra_id': Extra motor ID\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device XTrainerControlBoard --axes <mandatory_value> --port <mandatory_value> --baudrate <mandatory_value> --ids <mandatory_value> --extra_id <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device XTrainerControlBoard --axes <mandatory_value> --port <mandatory_value> --baudrate <mandatory_value> --ids <mandatory_value> --extra_id <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
