/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.2)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GENERATION is ON.

// Generated on: Sat Oct 10 22:34:05 2026


#include "XTrainerControlBoard_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(XTrainerControlBoardParamsCOMPONENT, "yarp.device.XTrainerControlBoard")
}


XTrainerControlBoard_ParamsParser::XTrainerControlBoard_ParamsParser()
{
    //Default value of parametermotorIds
    {
        m_motorIds.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_motorIds_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_motorIds.push_back(tempBot->get(i).asInt64());
            }
        }
        else
        {
             yError() <<"parameter 'motorIds' is not a properly formatted bottle";
        }
    }

}


std::vector<std::string> XTrainerControlBoard_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("port");
    params.push_back("baudrate");
    params.push_back("motorIds");
    params.push_back("extraId");
    params.push_back("encoderPulses");
    return params;
}


bool XTrainerControlBoard_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="port")
    {
        paramValue = m_port;
        return true;
    }
    if (paramName =="baudrate")
    {
        paramValue = std::to_string(m_baudrate);
        return true;
    }
    if (paramName =="motorIds")
    {
        std::ostringstream oss;
        oss << "( ";
        for (auto x : m_motorIds)
        {
            oss << x << " ";
        }
        oss << " )";
        paramValue = oss.str();
        return true;
    }
    if (paramName =="extraId")
    {
        paramValue = std::to_string(m_extraId);
        return true;
    }
    if (paramName =="encoderPulses")
    {
        paramValue = std::to_string(m_encoderPulses);
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string XTrainerControlBoard_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      XTrainerControlBoard_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(XTrainerControlBoardParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter port
    {
        if (config.check("port"))
        {
            m_port = config.find("port").asString();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'port' using value:" << m_port;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'port' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Name of the serial port";
            return false;
        }
        prop_check.unput("port");
    }

    //Parser of parameter baudrate
    {
        if (config.check("baudrate"))
        {
            m_baudrate = config.find("baudrate").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'baudrate' using value:" << m_baudrate;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'baudrate' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Baud rate of the serial port";
            return false;
        }
        prop_check.unput("baudrate");
    }

    //Parser of parameter motorIds
    {
        if (config.check("motorIds"))
        {
            {
                m_motorIds.clear();
                yarp::os::Bottle* tempBot = config.find("motorIds").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_motorIds.push_back(tempBot->get(i).asInt64());
                    }
                }
                else
                {
                     yCError(XTrainerControlBoardParamsCOMPONENT) <<"parameter 'motorIds' is not a properly formatted bottle";
                }
            }
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'motorIds' using value:" << m_motorIds;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'motorIds' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Motor IDs";
            return false;
        }
        prop_check.unput("motorIds");
    }

    //Parser of parameter extraId
    {
        if (config.check("extraId"))
        {
            m_extraId = config.find("extraId").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'extraId' using value:" << m_extraId;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'extraId' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Extra motor ID";
            return false;
        }
        prop_check.unput("extraId");
    }

    //Parser of parameter encoderPulses
    {
        if (config.check("encoderPulses"))
        {
            m_encoderPulses = config.find("encoderPulses").asInt64();
            yCInfo(XTrainerControlBoardParamsCOMPONENT) << "Parameter 'encoderPulses' using value:" << m_encoderPulses;
        }
        else
        {
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Mandatory parameter 'encoderPulses' not found!";
            yCError(XTrainerControlBoardParamsCOMPONENT) << "Description of the parameter: Number of encoder pulses per revolution";
            return false;
        }
        prop_check.unput("encoderPulses");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(XTrainerControlBoardParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(XTrainerControlBoardParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      XTrainerControlBoard_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: XTrainerControlBoard\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'port': Name of the serial port\n");
    doc = doc + std::string("'baudrate': Baud rate of the serial port\n");
    doc = doc + std::string("'motorIds': Motor IDs\n");
    doc = doc + std::string("'extraId': Extra motor ID\n");
    doc = doc + std::string("'encoderPulses': Number of encoder pulses per revolution\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device XTrainerControlBoard --port /dev/ttyACM0 --baudrate 2000000 --motorIds \" 1 2 4 5 6 7 8 \" --extraId 3 --encoderPulses 4096\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device XTrainerControlBoard --port /dev/ttyACM0 --baudrate 2000000 --motorIds \" 1 2 4 5 6 7 8 \" --extraId 3 --encoderPulses 4096\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
