/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.2)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GENERATION is ON.

// Generated on: Sat Oct 10 16:36:36 2026


#ifndef XTRAINERCONTROLBOARD_PARAMSPARSER_H
#define XTRAINERCONTROLBOARD_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class XTrainerControlBoard.
*
* These are the used parameters:
* | Group name | Parameter name | Type | Units | Default Value | Required | Description     | Notes |
* |:----------:|:--------------:|:----:|:-----:|:-------------:|:--------:|:---------------:|:-----:|
* | -          | axes           | int  | -     | -             | 1        | Number of axes. | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device XTrainerControlBoard --axes <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device XTrainerControlBoard --axes <mandatory_value>
* \endcode
*
*/

class XTrainerControlBoard_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    XTrainerControlBoard_ParamsParser();
    ~XTrainerControlBoard_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"XTrainerControlBoard"};
    const std::string m_device_name = {"XTrainerControlBoard"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 2;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_axes_defaultValue = {""};

    int m_axes = {0}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
