/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.2)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GENERATION is ON.

// Generated on: Sat Oct 10 22:34:05 2026


#ifndef XTRAINERCONTROLBOARD_PARAMSPARSER_H
#define XTRAINERCONTROLBOARD_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class XTrainerControlBoard.
*
* These are the used parameters:
* | Group name | Parameter name | Type        | Units | Default Value | Required | Description                             | Notes |
* |:----------:|:--------------:|:-----------:|:-----:|:-------------:|:--------:|:---------------------------------------:|:-----:|
* | -          | port           | string      | -     | /dev/ttyACM0  | 1        | Name of the serial port                 | -     |
* | -          | baudrate       | int         | -     | 2000000       | 1        | Baud rate of the serial port            | -     |
* | -          | motorIds       | vector<int> | -     | 1 2 4 5 6 7 8 | 1        | Motor IDs                               | -     |
* | -          | extraId        | int         | -     | 3             | 1        | Extra motor ID                          | -     |
* | -          | encoderPulses  | int         | -     | 4096          | 1        | Number of encoder pulses per revolution | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device XTrainerControlBoard --port /dev/ttyACM0 --baudrate 2000000 --motorIds \" 1 2 4 5 6 7 8 \" --extraId 3 --encoderPulses 4096
* \endcode
*
* \code{.unparsed}
* yarpdev --device XTrainerControlBoard --port /dev/ttyACM0 --baudrate 2000000 --motorIds \" 1 2 4 5 6 7 8 \" --extraId 3 --encoderPulses 4096
* \endcode
*
*/

class XTrainerControlBoard_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    XTrainerControlBoard_ParamsParser();
    ~XTrainerControlBoard_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"XTrainerControlBoard"};
    const std::string m_device_name = {"XTrainerControlBoard"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 2;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_port_defaultValue = {"/dev/ttyACM0"};
    const std::string m_baudrate_defaultValue = {"2000000"};
    const std::string m_motorIds_defaultValue = {"1 2 4 5 6 7 8"};
    const std::string m_extraId_defaultValue = {"3"};
    const std::string m_encoderPulses_defaultValue = {"4096"};

    std::string m_port = {"/dev/ttyACM0"};
    int m_baudrate = {2000000};
    std::vector<int> m_motorIds = { }; //Default values for lists are managed in the class constructor. It is highly recommended to provide a suggested value also for optional string parameters.
    int m_extraId = {3};
    int m_encoderPulses = {4096};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
